url: http://hackers-of-umass.github.io

# Site settings
title: Hackers of UMass
email: your-email@domain.com
description: "We're the hackers, builders, makers, and innovators of UMass Amherst."

# Colors
color:
  primary: ff6e00
  secondary: ff8600
  secondary-dark: 452411

# Social networks
social:
  - title: facebook
    url: https://facebook.com/groups/hackersofumass
  - title: github
    url: https://github.com/hackers-of-umass
  - title: slack
    url: https://umassacm.slack.com/messages/hackers-of-umass

# Build settings
markdown: kramdown
permalink: pretty
